version: '3.8'  # Specify the version of the Docker Compose file

services:
  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: postgres_db  # Name of the container
    environment:
      POSTGRES_USER: postgres  # Set the PostgreSQL user
      POSTGRES_PASSWORD: postgres  # Set the PostgreSQL password
      POSTGRES_DB: receba_delivery  # Set the name of the default database
    ports:
      - "5432:5432"  # Map port 5432 on the host to port 5432 on the container